name: CI Pipeline

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Repo
      uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: ./node_modules/.bin/eslint . -c eslint.config.js 
  
