name: CI Pipeline

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Repo
      uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.2
  
