name: CI Pipeline

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Repo
      uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Formatter
      run: ./node_modules/.bin/prettier "src/**/*.{js,ts,jsx,tsx,json}" --write
    - name: Run ESLint
      run: ./node_modules/.bin/eslint . -c eslint.config.js --fix
  
